version: "3"

services:
  gitea:
    container_name: gitea
    image: gitea/gitea
    ports:
      - 3000:3000
      - 2222:22
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: unless-stopped
