version: '3'

services:
  v2fly:
    container_name: v2fly
    image: v2fly/v2fly-core
    ports:
      - 8388:8388
      - 8388:8388/udp
    volumes:
      - ./config.json:/etc/v2fly/config.json
    command: run -c /etc/v2fly/config.json
    restart: unless-stopped
