version: "3"

services:
  nacos-server:
    container_name: nacos-server
    image: nacos/nacos-server
    environment:
      - PREFER_HOST_MODE=ip
      - MODE=standalone
    ports:
      - 8848:8848
      - 9848:9848
      - 9849:9849
