version: "3"

services:
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch
    ports:
      - 7700:7700
    volumes:
      - ./data:/meili_data
    environment:
      - MEILI_ENV=development
    restart: unless-stopped
